src/main/java/com/pde/session/SessionBean.java
package com.pde.session;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named("sessionBean")
@SessionScoped
public class SessionBean implements Serializable
{
	private static final long serialVersionUID = 5873457096373124257L;

	private long userId;
	private boolean loggedIn;
	private String username;
	private boolean isAdmin;

	public SessionBean()
	{
		userId = -1;
		loggedIn = false;
		username = "anonim";
		isAdmin = false;
	}
	
	public boolean isLoggedIn()
	{
		return loggedIn;
	}

	public void setLoggedIn(boolean loggedIn)
	{
		this.loggedIn = loggedIn;
	}

	public String getUsername()
	{
		return username;
	}

	public void setUsername(String username)
	{
		this.username = username;
	}

	public long getUserId()
	{
		return userId;
	}

	public void setUserId(long userId)
	{
		this.userId = userId;
	}

	public boolean isAdmin()
	{
		return isAdmin;
	}

	public void setAdmin(boolean isAdmin)
	{
		this.isAdmin = isAdmin;
	}
}

src/main/webapp/default/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    <body>
	    <ui:composition>
	    	<center>
				<span><br />Paweł Dec s9097 - paweldec123@gmail.com</span>
			</center>
	    </ui:composition>
    </body>
</html>

src/main/webapp/default/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">
    <body>
	    <ui:composition>
	    	<h:graphicImage library="images" name="logo.png" styleClass="header-logo" />
	    	<div class="logout-container">
		    	<p:outputLabel for="logoutBtn" value="Jesteś zalogowany jako: #{sessionBean.username}"
		    		rendered="#{sessionBean.loggedIn == true}" />&nbsp;
		    	<p:commandButton id="logoutBtn" value="Wyloguj" action="#{loginBean.logout()}" 
		    		rendered="#{sessionBean.loggedIn == true}" />
	    	</div>	
	    </ui:composition>
    </body>
</html>

src/main/webapp/default/menu.xhtml
<ui:composition 
	  xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui" >

	<h:outputScript name="menu.js" library="js" />

	<p:panelMenu>  
		<p:submenu label="Ogólne" styleClass="general" >
			<p:menuitem value="Ogłoszenia" outcome="/platform/modules/announcements/list.xhtml" icon="ui-icon-comment" />
			<p:menuitem value="Harmonogram" outcome="/platform/modules/schedule/index.xhtml" icon="ui-icon-pin-w" />
		</p:submenu>
		<p:submenu label="Klienci" styleClass="clients" >   
			<p:menuitem value="Przedstawiciele" outcome="/platform/modules/agents/list.xhtml" icon="ui-icon-person"/>  
			<p:menuitem value="Kontrahenci" outcome="/platform/modules/contractors/list.xhtml" icon="ui-icon-home"/>
		</p:submenu>
		<p:submenu label="Produkty" styleClass="products" >  
			<p:menuitem value="Produkty" outcome="/platform/modules/products/list.xhtml" icon="ui-icon-suitcase"/>
		</p:submenu>  
		<p:submenu label="Transakcje" styleClass="transactions" >
			<p:menuitem value="Nowa transakcja" outcome="/platform/modules/transactions/new.xhtml" icon="ui-icon-cart"/>
			<p:menuitem value="Lista oczekujących" outcome="/platform/modules/transactions/list.xhtml" icon="ui-icon-circle-zoomout"/>
		</p:submenu>
		<p:submenu label="Raporty" styleClass="reports" >  
			<p:menuitem value="Obroty" outcome="/platform/modules/reports/sales.xhtml" icon="ui-icon-bookmark"/>
		</p:submenu>
		<p:submenu label="Zarządzanie" styleClass="management" rendered="#{sessionBean.loggedIn and sessionBean.admin}" >  
			<p:menuitem value="Użytkownicy" outcome="/platform/modules/users/list.xhtml" icon="ui-icon-key" />
		</p:submenu>
	</p:panelMenu>
</ui:composition>